### ISSUE TITLE
Expose our JsonSerialization converter classes so users can leverage them in their own code

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/OctopusClients#128]
We have had a customer report an issue when trying to deserialize the `DeploymentProcessResource` using `Newtonsoft.Json` with the default serializer due to that we use custom resource converters and they're all marked as internal. It might be a good idea to make them available for customers to use in their own code.

Source: http://help.octopusdeploy.com/discussions/problems/51415

**Comment by Excommunicated** [comment]
+1 for this. We were also using the JsonSerialization.GetDefaultSerializerSettings() when converting data from Resources in our application as well. We Just updated to the latest client (4.11.0) to begin to make use of the Certificates management feature, and all our code is now broken due to not being able to get the Serializer Settings since Newtonsoft.Json is now internal to the Octopus.Client.

**Comment by benPearce1** [comment]
You can use the Octopus.Client.Serialization.JsonSerialization.SerializeObject method to serialise objects which will correctly use the Octopus.Client custom converters.
