### ISSUE TITLE
Remove IGet<TResource> from types that don't support Get(string[])

### ISSUE THREAD

**Issue by HamsterExAstris** [OctopusDeploy/OctopusClients#190]
There are some API methods that only support getting singular objects. For example, VariableSets.

I've posted [on the support board](http://help.octopusdeploy.com/discussions/questions/12595-getting-multiple-variable-sets-from-the-api-with-one-call) to ask whether this is an intentional API choice or a bug. Assuming that it's intentional, would you be open to a pull request to remove the Get(string[]) method from affected endpoints, rather than the client trying anyways and getting a 404 then throwing an OctopusResourceNotFoundException?

(This would definitely be for VariableSets. I'd want to review the API docs to look for other applicable endpoints too.)

**Comment by benPearce1** [comment]
Hi @HamsterExAstris,

This issue has been resolved.
Support for GET for a list of ID's was added to the following API endpoints in Octopus Server 3.17:
- Community Action Templates
- Deployment Processes
- Project Triggers

For the VariableSets, this was unable to support multiple ID GET due to performance issues. This operation in Octopus.Client now errors for this operation only. This was added in version 4.24.0 of the Client tools.

Regards
Ben
