### ISSUE TITLE
Octo.exe - create-release fail when there is special characters in project name

### ISSUE THREAD

**Issue by sl-williamdiesny** [OctopusDeploy/OctopusClients#335]
If I create a release with a project name **[TEST] MyProject** I got the following error :

```
octo create-release --server http://***** --apikey API-**** --project "[TEST] MyProject" --enableservicemessages --version 1.1.4 --deployto DEV --progress --ignoreexisting

Could not find a project named '[TEST] MyProject'; either it does not exist or you lack permissions to view it.
```
If I rename my project to **TEST MyProject**, the release create successfully.

I'm currently using **octo.exe 4.42.0** (Tried with **Windows 32-bit** & **.NET Core** version)
With an old version (3.5.4) it seems to be OK.

**Comment by mcasperson** [comment]
Hi @sl-williamdiesny, thanks for reporting this.

I've created an issue against the Octopus server, as the root of this issue is server side rather than client side. The new issue is https://github.com/OctopusDeploy/Issues/issues/5026. I'll close this issue and update the Octopus Server one with any progress.
