### ISSUE TITLE
Dotnet core 2.x

### ISSUE THREAD

**Issue by dlip** [OctopusDeploy/OctopusClients#347]
I'm using dotnet core 2.1.403 on mac and I cant use Octopus.Client.OctopusRepository. I think because its only compiled for 1.x?

```
dotnet add package Octopus.Client --version 4.42.2
using Octopus.Client.OctopusRepository; //error
```

**Comment by slewis74** [comment]
Hi, I think the issue is that in netcore you need to use [`Octopus.Client.OctopusAsyncRepository`](https://octopus.com/docs/api-and-integration/octopus.client#Octopus.Client-AsynchronousAPI(Octopus.Client4.0+)).

Octopus.Client has been built so the full framework version has both a sync and async repository, depending on your needs. In netcore though there's only an async HttpClient underneath, so we omit the `OctopusRepository`.

Hope that helps.

**Comment by dlip** [comment]
Yes, I think thats my problem. Thanks!
Maybe its worth adding to the docs to help noobs like me?

**Comment by slewis74** [comment]
No problems and an excellent point, I've put an update in the docs
